### ISSUE TITLE
3.3V Current

### ISSUE THREAD

**Issue by Milliways2** [Gadgetoid/Pinout2#109]
The statement "The 3v3, 3.3 volt, supply pin on the Pi has a max available current of about 50 mA" is incorrect for the B+ and later boards. (It may have been true for earlier models). It is possible to draw up to 1A - less current required for GPIO, SD Card etc. 800mA is certainly possible (5V power permitting.)

**Comment by RogueM** [comment]
cheers, for pointing that out. That info is only relevant to early models indeed. We'll make a note to the site accordingly in the next update.

**Comment by RogueM** [comment]
Done... will go live next update.
