### ISSUE TITLE
RedBear IoT pHAT

### ISSUE THREAD

**Issue by ChiHung** [Gadgetoid/Pinout2#112]
Hi,

We are the RedBear Team and thanks for posting the pinout of our IoT pHAT on https://pinout.xyz/pinout/iot_hat

A few updates
1. We have changed the name from “IoT HAT” to “IoT pHAT” since the Pi team said that the small form factor add-on board should not be called “HAT”.
2. There are some changes about the pinout in the final board
3. Our GitHub Repository is https://github.com/redbear/IoT_pHAT which has the latest information
4. They are available on sale at https://store.redbear.cc/product/rpi.html

Thank you and keep up the good work

Regards
Chi-Hung

**Comment by RogueM** [comment]
Done!
