### ISSUE TITLE
Sense HAT markup error

### ISSUE THREAD

**Issue by lurch** [Gadgetoid/Pinout2#26]
http://pinout.xyz/pinout/sense_hat displays "a 8Ã—8 RGB LED matrix" - I dunno if this is because of Unicode conversion / markup issues (which need fixing), or whether it'd be better to edit the SenseHAT 'source-file' to use the non-Unicode `x` character?

**Comment by Gadgetoid** [comment]
That should fix it!

**Comment by lurch** [comment]
Yup, seems to! But given the amount of overlap in the various layout.html files, maybe it'd be better to have a single 'master layout', and just make it "more translatable"?
Or are you really expecting different languages to use different fonts / css / js libraries etc.? ;-)
