### ISSUE TITLE
"installer" errors?

### ISSUE THREAD

**Issue by lurch** [Gadgetoid/Pinout2#29]
The "one-line installer" on http://pinout.xyz/pinout/unicorn_hat and http://pinout.xyz/pinout/display_o_tron_3000 pipes the retrieved file to bash, but the ` | bash` seems to be missing on:
* http://pinout.xyz/pinout/explorer_hat_pro
* http://pinout.xyz/pinout/pibrella
* http://pinout.xyz/pinout/explorer_hat

**Comment by Gadgetoid** [comment]
Zoiks! That's surely a bug.

**Comment by lurch** [comment]
...and I guess this is another "fix" that won't get automatically translated to other languages? ;-)
(assuming of course that `curl` and `bash` remain named as they are in e.g. Italian)

**Comment by RogueM** [comment]
that's undoutedly my doing. I will fix as I am to blame. And no, since nothing is shared between locale then it has to be retro-fitted in all... it's not a major pain, but it definitely isn't automatic.

**Comment by lurch** [comment]
Now fixed and published.
