### ISSUE TITLE
flags missing at it.pinout.xyz

### ISSUE THREAD

**Issue by RogueM** [Gadgetoid/Pinout2#51]
as per title flags missing at it.pinout.xyz on 2015-11-14

**Comment by Gadgetoid** [comment]
Whoops! It wasn't in my build list so the HTML didn't get updated when I changed all the filenames for the flags. Fixed!

**Comment by lurch** [comment]
> It wasn't in my build list...

Does that mean there's some part of pinout that isn't currently in github? Would it make sense to add that to the repo too? Or is it just a script that e.g. updates and uploads all the files to pinout.xyz (and subdomains) ? (which would obviously be specific to your particular hosting setup)
