### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Maslor** [Gadgetoid/Pinout2#6]
Do you need an english to portuguese (pt-PT) translation? Let me know if you do as I may have the time to work on it.

**Comment by RogueM** [comment]
@Maslor yes, thanks for offering your help, I'm sure that would be welcome!

@Gadgetoid is starting to deploy the localised versions of pinout at this stage via pinout.xyz and I'm sure it would help many people in your country if they had the opportunity to read the boards description in their language!

**Comment by Gadgetoid** [comment]
@Maslor absolutely! I've finally had time to prepare pinout for a proper translation and update. Every translation will get its own subdomain on pinout.xyz (pt.pinout.xyz) and I'll be working on making sure the translated pages are well linked and indexed so people can find them.

**Comment by RogueM** [comment]
@Gadgetoid, you can close this issue I think, for clarity.
