### ISSUE TITLE
Cheeky overlay request (IQAudIO boards)

### ISSUE THREAD

**Issue by tobyweston** [Gadgetoid/Pinout2#86]
I'd love to see the [IQAudIO](http://www.iqaudio.com/downloads/IQaudIO.pdf) boards represented on the pinout. Mostly because I can't figure out the pins for myself :smile:

**Comment by RogueM** [comment]
the Pi-DigiAMP+ is 100% equivalent to a Pi-Dac+/Pi-AMP+ combo from pinout's point of view. That's not to say I don't think it shouldn't be covered, just that besides the 'long' description it would be exactly the same as http://pinout.xyz/pinout/pi_dac
